spring.application.name=CryptoTracker

# ===== Gmail SMTP Configuration =====
# STEP 1: Gmail ID (Set as Environment Variable GMAIL_USER)
spring.mail.username=${GMAIL_USER}
# STEP 2: Gmail App Password (Set as Environment Variable GMAIL_PASS)
spring.mail.password=${GMAIL_PASS}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
